### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by dnkennedy** [ReproNim/fsl_seg_to_nidm#7]
error: requests 2.24.0 is installed but requests>=2.25.0 is required by {'python-gitlab'}

**Comment by dbkeator** [comment]
Give the latest version (0.0.2).  I've fixed the version of requests>=2.25.0.

**Comment by dnkennedy** [comment]
Thanks, @dbkeator

**Comment by dnkennedy** [comment]
So, I can now install, the keys were to initiate a 'clean' environment, and I had to pip install click. So I will close this, and file a new issue regarding the click dependency...
